### ISSUE TITLE
[ENHANCEMENT] Header & Footer

### ISSUE THREAD

**Issue by Flavourized** [DRE2N/BroadcastXS#1]
Hey! I'm Kroh from spigotmc.

So i'm really digging the centered chat update :D

An issuee (maybe?) would include that i can't seem to figure out how to implement a header and footer for the message. E.G If i wanted the message to look like this:

&8&m-----------------------------------------------------
                            My attempt at center chat
&8&m-----------------------------------------------------

I tried messing with the prefix and then adding the second line, but that didnt work out :/
If there is a way to implement this, please let me know!

**Comment by Flavourized** [comment]
Okay. I solved problem 1 with the centered texts by using <br>. From the config i was under the impression that <br> did NOT break lines in centered text, however it does, which allows me to split the words up so it stays center.

Here is the config line:

- "centered:&8&m-----------------------------------------------------<br>&aVisit our website for the latest news, <br> forums and more at &chttp://www.mywebsite.net<br>&8&m-----------------------------------------------------"

And it gives a centered text (gotta fix colors)



But i would still really appreciate a way where we can set a default header/footer for all messages

**Comment by Flavourized** [comment]
Alongside that, if you could make it so the centered: and other chat types worked in header/footer aswell

**Comment by Sataniel98** [comment]
As long as they make sense (not titles /actionBars), I don't see why not.
