### ISSUE TITLE
Adding clickable messages 

### ISSUE THREAD

**Issue by Flavourized** [DRE2N/BroadcastXS#10]
Hi, hope you're killing those exams!

Had a suggestion for clickable commands from an auto message. E.G if this was a message:

`- centered:<br>&aWant to turn the &2&lPRO&7-&a&lTIPS&a off?<br>&bUse command &c/toggle protips`

i could add something like bbcode style or whatever is easiest to parse:

`- centered:<br>&aWant to turn the &2&lPRO&7-&a&lTIPS&a off?<br>&bUse command <clickable>&c/toggle protips;tooltip message here; Command to Run here</clickable>`

I am unsure of how you want to make it parse, but the syntax would be:
`
<clickable>Chatbox message here ; Tool tip message here ; command to run here </clickable>`

and color codes should be supported, and it shouldnt break the nice centering of messages. 

Thanks :)

**Comment by Flavourized** [comment]
Also if you could make `<br>` inside the tooltip message (if that is possible) work.

Alongside that multiple commands inside the commands to run here, commands could be separated by commas or another symbol

**Comment by Sataniel98** [comment]
Would be a nice feature, but I'm not sure if I'd like to work on something like that in the forseeable future. Maybe after I reworked my general library that provides most of this stuff (like centering messages) sothat it supports them.

**Comment by Sataniel98** [comment]
Now supported through the MiniMessage format.
