### ISSUE TITLE
[ENHANCEMENT] Allowing user to edit messages with in game commands

### ISSUE THREAD

**Issue by Flavourized** [DRE2N/BroadcastXS#12]
Allowing user to edit messages with in game command. So we can use scripts and such to update messages instead of having to manually edit each time. 

Possible commands:
/bxs edit [msgIndex] [newMsg]

and we would have to replace [newMsg] with the whole message we want, including the formatting tags such as centered:, <br>, etc. 

To add on, for other server, allowing the header, footer, and prefix to be changed with an in game command. This would really be useful

**Comment by Flavourized** [comment]
I guess, adding on to this, would have the command to remove a message index.

/bxs remove <index>

**Comment by Sataniel98** [comment]
Added in v3.2
