### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by CraftedBalance** [DRE2N/BroadcastXS#13]
Hello! 
I've got a pretty simple question, is there a way to broadcast a message in game that's not in the config broadcast list?

Ex: /broadcast hi, everyone!

- Balance

**Comment by Sataniel98** [comment]
Yes, that's indeed possible. The command is "/bxs bc [...]" and it requires the permission node "bxs.broadcast". You can enter either a number sothat it broadcasts a list entry from your config or custom text. You can use all formatting codes that can be used in the config as well: "/bxs bc actionBar:&4&lRESTART IN 20 SECONDS!" for example will broadcast a red, bold **RESTART IN 20 SECONDS!** action bar message to all players.

**Comment by CraftedBalance** [comment]
Thanks!
