### ISSUE TITLE
[ENHANCEMENT] PAPI and/or mvdwPAPI soft depend

### ISSUE THREAD

**Issue by Flavourized** [DRE2N/BroadcastXS#14]
Self-explanatory, would just like to use some placeholders in auto-broadcasts!

**Comment by Sataniel98** [comment]
Damn.
![](https://media0.giphy.com/media/QZFJCAojAg9TG/giphy.gif)
Flavourized is back.

That means work.

I'll see what I can do ;)

**Comment by Flavourized** [comment]
<3

**Comment by Sataniel98** [comment]
Added in v3.2.

**Comment by Flavourized** [comment]
@Sataniel98 I cant seem to finnd where the download for 3.2 is.

spigotpage shows 3.1.2 last edit  in may

**Comment by Sataniel98** [comment]
Source is online, I'll do a few tests before posting it to SpigotMC.
