### ISSUE TITLE
[something?] Centered msgs are trolling me :(

### ISSUE THREAD

**Issue by Flavourized** [DRE2N/BroadcastXS#15]
Hi

So you know me and my pickyness. And this is not an issue, but idk what it is. It tilts me though

Here is the screenie:
http://prntscr.com/hjq2am

Here is the config (msg from screenie is on line 30): 
https://hastebin.com/ajunomejac.xml

Am i being trolled or am i just too ocd? :(

**Comment by Sataniel98** [comment]
There's one redundant &a in the second line. I'm not sure if it helps but I'd try removing it ^^

**Comment by Flavourized** [comment]
Removed it and im still getting trolled. Your lib hates me :(

**Comment by Flavourized** [comment]
Okay, so i think there is another issue with centering messages.. 


So if you take a look at this screenshot: http://prntscr.com/imgzw1

You will notice that the first 'DRUGRUN' has more space on the right side. The second DRUGRUN has equal space on both sides. The easiest way to show this is by putting the picture in gimp or paint and then using a ruler to count the pixels. 


Here is the format for the first DRUGRUN: 
`centered:<br>&f⟩&7⟩&8⟩ &a&lDRUG&2&lRUN &8⟨&7⟨&f⟨`

Here is the format for the second DRUGRUN:
`centered:<br>&f &f &f &f &f &f⟩&7⟩&8⟩ &a&lDRUG&2&lRUN &8⟨&7⟨&f⟨`



Could it be an issue with bolded letters? This issue still occurs if the arrow characters are not present.

**Comment by Flavourized** [comment]
i dont know why it closed it. I didn't mean to close it

**Comment by Flavourized** [comment]
ok ive determined that this is caused by me being too ocd and i should just learn to deal with it.

**Comment by Sataniel98** [comment]
I tried it once again and it worked well for some reason. Not sure what I did differently, I can't see your config anymore :(
