### ISSUE TITLE
Add 1.16.x RGB support.

### ISSUE THREAD

**Issue by martijnmelchers** [DRE2N/BroadcastXS#18]
With 1.16.x Minecraft now supports RGB colors in the chat, I'd like to see it added so it can be used it plugins. It currently won't work as shown below:

![image](https://user-images.githubusercontent.com/6060006/95354636-ed226a80-08c4-11eb-8cf3-93df3180a9d7.png)

The color before ReflexNetwork should be corrected to the RGB color supplied.

**Comment by Sataniel98** [comment]
It requires no more than an update of the MiniMessage library, will do that sooner or later.

**Comment by martijnmelchers** [comment]
Could this happen sooner, I would like to use this feature.

**Comment by Sataniel98** [comment]
There's no stable build of the library out yet.
