### ISSUE TITLE
[BUG] Config being wiped if reload fails

### ISSUE THREAD

**Issue by Flavourized** [DRE2N/BroadcastXS#2]
Bug #2

If there is a yaml error, or any other error with formatting, the plugin deletes the old config and creates a fresh one..

Could you make it where it will save the old config under a different name so it's not lost completely?

**Comment by Sataniel98** [comment]
Did you remove or modify "configVersion: 2"?

**Comment by Flavourized** [comment]
Nope. Whenever there is a YAML parse error, it wipes the config

**Comment by Sataniel98** [comment]
Confirmed and fixed. It's actually a problem in my standard library, so it occurred in all of my plugins. Thank you for your report :)

https://github.com/DRE2N/BRCommons/commit/9f64d0bbad9c6075ceb0d1c502f3bcb9e1d512d7
