### ISSUE TITLE
[ENHANCEMENT] Ability to one-time broadcast a message in game

### ISSUE THREAD

**Issue by Flavourized** [DRE2N/BroadcastXS#4]
Considering how useful the center messages feature on this plugin is, a way to broadcast a custom message that is centered (with the option to use Header/Footer) would be really neat to have!

/bxs bc <header/footer(true/false)> <center(true/false> <message>

**Comment by Sataniel98** [comment]
It seems like I'm getting material for another "big" update ^^

**Comment by Sataniel98** [comment]
Did it. I didn't add an argument to adjust the header/footer, though, but you can format it just like in the config file with <br>, center:, actionBar: etc.

I will publish a release at SpigotMC as soon as I've tested it.
