### ISSUE TITLE
[ENHANCEMENT] Per group broadcasts

### ISSUE THREAD

**Issue by lovecu** [DRE2N/BroadcastXS#5]
Like the name says, we should be able to attach a permission to a message or multiple messages and only groups with that permission will receive that message. 

'1':
  message: "centered:this is a test"
  permission: group1 #bxs.messages.group1 default:false

**Comment by Sataniel98** [comment]
Sorry, but I'd rather keep the configuration as simple as it is. The "XS" has its point.
