### ISSUE TITLE
Async error

### ISSUE THREAD

**Issue by Flavourized** [DRE2N/BroadcastXS#6]
Version: 3.0
Server: Paper 1.9.4 (Build 773)

Error: http://pastebin.com/XqUDGHcv
Config: http://pastebin.com/SHkUEYdy

Put the config and lang files thru a yaml parser with no errors. Have not replaced the bxs3.jar file yet.

**Comment by Sataniel98** [comment]
Wow, that's weird. I think I know the problem, give me a minute or two.

**Comment by Sataniel98** [comment]
BXS 3.0.1 is available at SpigotMC as of now, please tell me if it doesn't work as intended.

**Comment by Flavourized** [comment]
Works without errors (I think). Im getting a similar error with mcMMO, but the broadcastXS plugin is working as intended. Sorry for the late reply, doing some travelling.

**Comment by Sataniel98** [comment]
To be honest, I'm not even sure if this is a bug of a plugin or if I'm just dodging a bug of the server software. Broadcasting a message shouldn't lead to loading chunks, it should be thread safe in general (which means it shouldn't cause problems if used asynchronously). And I have no idea why command blocks need to get broadcasts. So yes, I can well imagine that you get the problem with other plugins, too.
