### ISSUE TITLE
[ENHANCEMENT] Random Broadcast

### ISSUE THREAD

**Issue by Flavourized** [DRE2N/BroadcastXS#7]
Adding a single line option to have messages broadcast randomly from what has not been broadcasted (not sure how to say this.). E.G Broadcast first message randomly, and then take that message off the array of messages to randomly broadcast. Once all messages have been randomly broadcasted, reset the array except for the last randomly broadcasted message, and do the random thing again.. You're the programmer, you know what to do :P

**Comment by Sataniel98** [comment]
What exactly would be the benefit of this, though?

**Comment by Flavourized** [comment]
That's a good question.. I know you're about keeping it XS, just figured it was a pretty simple feature that a lot of the other announcers have in common. I have no problem with the current setup :p
