### ISSUE TITLE
Removing /broadcast from default command

### ISSUE THREAD

**Issue by Flavourized** [DRE2N/BroadcastXS#8]
Hey Sata,

I wanted to know if you could remove /broadcast as an alias. Kind of a pain when we have to go through manually and remove it just so we can use essentials broadcast. /bxs is pretty standard for me, but all of my other plugins use /broadcast to deliver some messages and it gets annoying when the alias is set for /bxs

**Comment by Sataniel98** [comment]
Okay, I guess nobody is using it anyway. I'll remove it in the next release.

**Comment by Flavourized** [comment]
Thanks a bunch <3 Best dev
