### ISSUE TITLE
Command to toggle automessages (For players)

### ISSUE THREAD

**Issue by Flavourized** [DRE2N/BroadcastXS#9]
Few players have been asking for a command to toggle auto message visibility in their chat. 

e.g /bxs off or /bxs toggle

**Comment by Sataniel98** [comment]
When you gotta learn for your exams and *FINALLY* someone has mercy and gives you an excuse to do something else.
![](https://media.giphy.com/media/1Z02vuppxP1Pa/giphy.gif)

I "messed around" with it a bit and tested it one time - it doesn't seem to work well with /bxs reload at the moment but I'm sure I'll be able to fix this sometime soon.

**Comment by Sataniel98** [comment]
Link to the new release:

http://feuerstern.bplaced.net/repo/io/github/dre2n/broadcastxs/3.1/broadcastxs-3.1.jar

**Comment by Flavourized** [comment]
<3
